### PR TITLE
Initial LG Cast Integration

### PR DESCRIPTION
**Pull request by lgcast-dev**

### CODE REVIEW

**Comment by hieuttmatech** [comment]
@lgcast-dev can you rebuild LGCast GStreamerForLGCast with Enable bitcode.
and BUILD_LIBRARY_FOR_DISTRIBUTION = YES

**Comment by lgcast-dev** [comment]
@hieuttmatech We changed the BUILD_LIBRARIES_FOR_DISTRIBUTION flag to YES. And bitcode is already enabled. Please refer to the PR link below.
 - https://github.com/ConnectSDK/Connect-SDK-iOS-Core/pull/71
Thank you.

**Comment by hieuttmatech** [comment]
oh. tks my bro. great job!

**Comment by hieuttmatech** [comment]
but if it right. can you rebuild LGCast GStreamerForLGCast with  BUILD_LIBRARY_FOR_DISTRIBUTION = YES. disable bitcode :( .
https://developer.apple.com/documentation/Xcode-Release-Notes/xcode-14-release-notes

**Comment by hieuttmatech** [comment]
> @hieuttmatech We changed the BUILD_LIBRARIES_FOR_DISTRIBUTION flag to YES. And bitcode is already enabled. Please refer to the PR link below.
> 
> * [Update README.md and LGCast v1.3.3 Connect-SDK-iOS-Core#71](https://github.com/ConnectSDK/Connect-SDK-iOS-Core/pull/71)
>   Thank you.

seem LGCast.framework still don't use bitcode. when having time, can you rebuild for me

**Comment by hieuttmatech** [comment]
@lgcast-dev can you send me source code off GStreamerForLGCast and LGCast framework. I will build binary framework(xcframework) for use my project. tks

**Comment by hieuttmatech** [comment]
hi @lgcast-dev : I have problem when playing m3u8 file. LG TV cannot play the file. ( https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8 ). Can you support me ?

**Pull request merged**
